include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_build_context_synchronously: ignore

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    always_declare_return_types: true

